export const dynamic = "force-dynamic";

export async function GET() {
  return Response.json([
    {
      id: "primary-care",
      name: "Primary Care",
      icon: "🏥",
      head: "Dr. Sarah Chen",
      doctor_count: 4,
      sessions_today: 24,
      doctors: [
        {
          id: "dr-chen",
          name: "Dr. Sarah Chen",
          title: "MD",
          specialty: "Family Medicine",
          initials: "SC",
          color: "#14b8a6",
          rating: 4.8,
          review_count: 142,
          sessions_week: 38,
          status: "available",
          years_exp: 12,
          languages: ["English", "Mandarin"],
          next_available: "Today 2:30 PM",
          bio: "Board-certified family physician specialising in preventive care and chronic disease management. Dr. Chen completed her residency at UCSF and has a particular interest in health equity and underserved communities.",
          reviews: [
            { author: "Patient M.", rating: 5, date: "Jun 10, 2026", text: "Dr. Chen took the time to listen and explain everything clearly. I never feel rushed." },
            { author: "Patient R.", rating: 5, date: "Jun 8, 2026",  text: "She's been my family doctor for 5 years and I wouldn't go anywhere else. Excellent bedside manner." },
            { author: "Patient K.", rating: 4, date: "Jun 3, 2026",  text: "Very knowledgeable. Wait times can be a bit long but absolutely worth it." },
          ],
        },
        {
          id: "dr-osei",
          name: "Dr. Kwame Osei",
          title: "MD, MPH",
          specialty: "Internal Medicine",
          initials: "KO",
          color: "#2DD4BF",
          rating: 4.6,
          review_count: 89,
          sessions_week: 31,
          status: "busy",
          years_exp: 8,
          languages: ["English", "Twi"],
          next_available: "Tomorrow 9:00 AM",
          bio: "Internist with a focus on preventive medicine and population health. Dr. Osei holds an MPH from Johns Hopkins and has published research on hypertension management in high-risk populations.",
          reviews: [
            { author: "Patient D.", rating: 5, date: "Jun 12, 2026", text: "Very thorough and genuinely cares about prevention, not just treating symptoms." },
            { author: "Patient A.", rating: 4, date: "Jun 6, 2026",  text: "Great doctor. Explains everything in plain language and never dismisses concerns." },
            { author: "Patient F.", rating: 5, date: "Jun 1, 2026",  text: "Dr. Osei caught something three other doctors missed. Incredibly sharp." },
          ],
        },
        {
          id: "dr-park",
          name: "Dr. Ji-Yeon Park",
          title: "MD",
          specialty: "Family Medicine",
          initials: "JP",
          color: "#8b5cf6",
          rating: 4.9,
          review_count: 203,
          sessions_week: 44,
          status: "available",
          years_exp: 16,
          languages: ["English", "Korean"],
          next_available: "Today 4:00 PM",
          bio: "Highly experienced family physician and clinical educator. Dr. Park has been recognised five years running as a top doctor by the regional health council, with a particular focus on women's health and geriatric care.",
          reviews: [
            { author: "Patient L.", rating: 5, date: "Jun 13, 2026", text: "Absolutely outstanding. Dr. Park is the gold standard for what a doctor should be." },
            { author: "Patient B.", rating: 5, date: "Jun 11, 2026", text: "She remembered every detail from my last visit without looking at notes. Impressive." },
            { author: "Patient N.", rating: 5, date: "Jun 9, 2026",  text: "The most compassionate and competent physician I have ever seen." },
          ],
        },
        {
          id: "dr-williams",
          name: "Dr. Marcus Williams",
          title: "DO",
          specialty: "Osteopathic Medicine",
          initials: "MW",
          color: "#f59e0b",
          rating: 4.7,
          review_count: 118,
          sessions_week: 29,
          status: "away",
          years_exp: 10,
          languages: ["English", "Spanish"],
          next_available: "Wed Jun 18 @ 10:00 AM",
          bio: "Osteopathic physician combining conventional medicine with a holistic approach to musculoskeletal health. Dr. Williams completed a fellowship in integrative medicine and has a large patient following for back and joint issues.",
          reviews: [
            { author: "Patient T.", rating: 5, date: "Jun 9, 2026",  text: "Fixed my chronic back pain in three visits when no one else could after years of trying." },
            { author: "Patient C.", rating: 4, date: "Jun 5, 2026",  text: "Great holistic approach. Treats the whole person, not just the symptom." },
            { author: "Patient H.", rating: 5, date: "May 29, 2026", text: "Dr. Williams is incredibly skilled. Highly recommend for anyone with chronic pain." },
          ],
        },
      ],
    },
    {
      id: "cardiology",
      name: "Cardiology",
      icon: "🫀",
      head: "Dr. Yemi Adeyemi",
      doctor_count: 3,
      sessions_today: 14,
      doctors: [
        {
          id: "dr-adeyemi",
          name: "Dr. Yemi Adeyemi",
          title: "MD, FACC",
          specialty: "Interventional Cardiology",
          initials: "YA",
          color: "#ef4444",
          rating: 4.9,
          review_count: 218,
          sessions_week: 22,
          status: "available",
          years_exp: 18,
          languages: ["English", "Yoruba"],
          next_available: "Today 3:15 PM",
          bio: "Fellowship-trained interventional cardiologist with expertise in complex PCI and structural heart disease. Dr. Adeyemi has performed over 3,000 catheterisation procedures and leads the clinic's heart failure programme.",
          reviews: [
            { author: "Patient G.", rating: 5, date: "Jun 14, 2026", text: "Dr. Adeyemi saved my life. His calm confidence during a crisis was extraordinary." },
            { author: "Patient V.", rating: 5, date: "Jun 10, 2026", text: "World-class cardiologist. I drive 90 minutes to see him — absolutely worth it." },
            { author: "Patient O.", rating: 5, date: "Jun 7, 2026",  text: "Extraordinarily thorough. He reviewed my entire cardiac history before our first appointment." },
          ],
        },
        {
          id: "dr-russo",
          name: "Dr. Elena Russo",
          title: "MD",
          specialty: "Cardiac Electrophysiology",
          initials: "ER",
          color: "#3b82f6",
          rating: 4.7,
          review_count: 94,
          sessions_week: 18,
          status: "busy",
          years_exp: 11,
          languages: ["English", "Italian"],
          next_available: "Thu Jun 19 @ 8:30 AM",
          bio: "Electrophysiologist specialising in arrhythmia management and catheter ablation. Dr. Russo trained at the Cleveland Clinic and has a particular interest in atrial fibrillation and sudden cardiac death prevention.",
          reviews: [
            { author: "Patient S.", rating: 5, date: "Jun 8, 2026",  text: "My AFib is finally under control thanks to Dr. Russo. Life-changing." },
            { author: "Patient P.", rating: 4, date: "Jun 4, 2026",  text: "She explained my options clearly and didn't push for the most aggressive path." },
            { author: "Patient W.", rating: 5, date: "May 31, 2026", text: "An exceptional specialist. Caring and technically superb." },
          ],
        },
        {
          id: "dr-lee",
          name: "Dr. James Lee",
          title: "MD, PhD",
          specialty: "Preventive Cardiology",
          initials: "JL",
          color: "#0D7377",
          rating: 4.6,
          review_count: 76,
          sessions_week: 15,
          status: "available",
          years_exp: 9,
          languages: ["English", "Korean", "French"],
          next_available: "Today 5:00 PM",
          bio: "Physician-scientist combining clinical cardiology with translational research in lipid metabolism and atherosclerosis prevention. Dr. Lee's lab has published 40+ papers on PCSK9 inhibitors and cardiovascular risk reduction.",
          reviews: [
            { author: "Patient I.", rating: 5, date: "Jun 13, 2026", text: "Dr. Lee brought a scientific rigour to my care I'd never experienced before." },
            { author: "Patient U.", rating: 5, date: "Jun 7, 2026",  text: "I came for a second opinion and he completely rethought my treatment plan for the better." },
            { author: "Patient E.", rating: 4, date: "Jun 2, 2026",  text: "Brilliant doctor. Sometimes a bit technical but always willing to simplify if you ask." },
          ],
        },
      ],
    },
    {
      id: "neurology",
      name: "Neurology",
      icon: "🧠",
      head: "Dr. Priya Menon",
      doctor_count: 2,
      sessions_today: 9,
      doctors: [
        {
          id: "dr-menon",
          name: "Dr. Priya Menon",
          title: "MD, PhD",
          specialty: "Cognitive Neurology",
          initials: "PM",
          color: "#a78bfa",
          rating: 4.8,
          review_count: 167,
          sessions_week: 26,
          status: "available",
          years_exp: 14,
          languages: ["English", "Hindi", "Malayalam"],
          next_available: "Today 1:45 PM",
          bio: "Specialist in Alzheimer's disease and memory disorders, with dual training in neurology and cognitive psychology. Dr. Menon runs the clinic's Memory Care programme and is principal investigator on two NIH-funded trials.",
          reviews: [
            { author: "Patient A.", rating: 5, date: "Jun 11, 2026", text: "She gave our family hope and a clear roadmap after my mother's diagnosis. Incredible." },
            { author: "Patient X.", rating: 5, date: "Jun 8, 2026",  text: "Dr. Menon is the most thorough and compassionate neurologist I have encountered." },
            { author: "Patient Q.", rating: 5, date: "Jun 3, 2026",  text: "Research-level knowledge combined with genuine warmth. Exceptional." },
          ],
        },
        {
          id: "dr-patel-n",
          name: "Dr. Arjun Patel",
          title: "MD",
          specialty: "Movement Disorders",
          initials: "AP",
          color: "#f472b6",
          rating: 4.5,
          review_count: 58,
          sessions_week: 19,
          status: "busy",
          years_exp: 7,
          languages: ["English", "Gujarati", "Hindi"],
          next_available: "Fri Jun 20 @ 11:00 AM",
          bio: "Specialist in Parkinson's disease, essential tremor, and related movement disorders. Dr. Patel completed his movement disorders fellowship at Columbia and is experienced in DBS candidacy evaluation.",
          reviews: [
            { author: "Patient Z.", rating: 5, date: "Jun 9, 2026",  text: "Dr. Patel adjusted my Parkinson's medication and the improvement was immediate." },
            { author: "Patient Y.", rating: 4, date: "Jun 4, 2026",  text: "Very dedicated. Getting an appointment quickly can be challenging but worth the wait." },
            { author: "Patient J.", rating: 5, date: "May 28, 2026", text: "I trust him completely with my care. He stays current with the latest research." },
          ],
        },
      ],
    },
    {
      id: "orthopedics",
      name: "Orthopedics",
      icon: "🦴",
      head: "Dr. Marcus Williams",
      doctor_count: 3,
      sessions_today: 17,
      doctors: [
        {
          id: "dr-torres",
          name: "Dr. Isabel Torres",
          title: "MD, FAAOS",
          specialty: "Sports Medicine & Joint Reconstruction",
          initials: "IT",
          color: "#fb923c",
          rating: 4.9,
          review_count: 244,
          sessions_week: 35,
          status: "available",
          years_exp: 15,
          languages: ["English", "Spanish"],
          next_available: "Today 2:00 PM",
          bio: "Fellowship-trained orthopaedic surgeon with specialisation in minimally invasive knee and hip replacement. Dr. Torres is team physician for two local professional sports organisations and has an extensive sports injury practice.",
          reviews: [
            { author: "Patient B.", rating: 5, date: "Jun 14, 2026", text: "I was walking without pain 4 weeks after my knee replacement. Remarkable." },
            { author: "Patient C.", rating: 5, date: "Jun 11, 2026", text: "Best surgeon I've ever encountered. Clear communication and superb outcomes." },
            { author: "Patient D.", rating: 5, date: "Jun 8, 2026",  text: "Dr. Torres is the reason I can still play tennis at 62. Truly gifted." },
          ],
        },
        {
          id: "dr-nguyen-o",
          name: "Dr. Linh Nguyen",
          title: "MD",
          specialty: "Spine Surgery",
          initials: "LN",
          color: "#4a7070",
          rating: 4.6,
          review_count: 103,
          sessions_week: 21,
          status: "available",
          years_exp: 12,
          languages: ["English", "Vietnamese"],
          next_available: "Tomorrow 10:30 AM",
          bio: "Spine surgeon with expertise in minimally invasive techniques for degenerative disc disease, stenosis, and scoliosis. Dr. Nguyen trained at Duke and has a particular focus on motion-preserving procedures over fusion.",
          reviews: [
            { author: "Patient E.", rating: 5, date: "Jun 10, 2026", text: "Three levels of stenosis corrected through tiny incisions. Minimal scarring and fast recovery." },
            { author: "Patient F.", rating: 4, date: "Jun 6, 2026",  text: "Technically excellent. Pre-op explanations were very thorough and put me at ease." },
            { author: "Patient G.", rating: 5, date: "Jun 2, 2026",  text: "I avoided a fusion because Dr. Nguyen offered a better option. Forever grateful." },
          ],
        },
        {
          id: "dr-kim-o",
          name: "Dr. David Kim",
          title: "MD",
          specialty: "Hand & Upper Extremity",
          initials: "DK",
          color: "#14b8a6",
          rating: 4.7,
          review_count: 87,
          sessions_week: 24,
          status: "off",
          years_exp: 9,
          languages: ["English", "Korean"],
          next_available: "Mon Jun 22 @ 9:00 AM",
          bio: "Hand surgery specialist treating carpal tunnel, trigger finger, wrist fractures, and tendon injuries. Dr. Kim uses nerve conduction studies in-house to expedite diagnosis and has a high patient satisfaction rate for outpatient hand procedures.",
          reviews: [
            { author: "Patient H.", rating: 5, date: "Jun 7, 2026",  text: "My carpal tunnel surgery was quick, painless, and the recovery was exactly as described." },
            { author: "Patient I.", rating: 5, date: "Jun 1, 2026",  text: "Exceptional technical skill for such a delicate surgery. Highly recommend." },
            { author: "Patient J.", rating: 4, date: "May 27, 2026", text: "Good outcome. The pre-op wait list is long but the results speak for themselves." },
          ],
        },
      ],
    },
  ]);
}
